.\" (C) Copyright 2018 Pavel Rehak <pavel-rehak@email.cz>,
.\"
.TH PPA-DOWNLOAD-COUNTER 1 "May 20 2018"
.\" Please adjust this date whenever revising the manpage.
.\"
.SH NAME
PPA Download Counter \-
.SH SYNOPSIS
.B ppa-download-counter
.RI [ option ]
.SH DESCRIPTION
.B ppa-download-counter
.PP
.SH OPTIONS
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show the ppa-download-counter version.
.SH LINKS
.TP
.B PPA Download Counter Homepage
\fI\%https://github.com/pavreh/ppa-download-counter/\fP
.TP
.B PPA Download Counter PPA
\fI\%https://launchpad.net/~pavreh/+archive/ubuntu/ppa/\fP
.SH AUTHOR
2018, Pavel Rehak
